#baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme="basic"

DefaultContentLanguage = "es"

[languages]

 [languages.it]
    title = "Guías Formentera"
    weight = 3

  [languages.en]
    title = "Guías Formentera"
    weight = 2

  [languages.es]
    title = "Guías Formentera"
    weight = 1

[menu]

#es

  [[languages.es.menu.main]]
   identifier = "info"
   name = "Info"
   title = "Info"
   url = "/info"
   weight = 10
 [[languages.es.menu.main]]
   identifier = "articulos"
   name = "Artículos"
   title = "Artículos"
   url = "/articulos/"
   weight = 20
[[languages.es.menu.main]]
   identifier = "fotos"
   name = "Fotos"
   title = "Fotos"
   url = "/fotos/"
   weight = 30
[[languages.es.menu.main]]
  identifier = "reservas"
  name = "Reservar"
  title = "Reservar"
  url = "/reservas/"
  weight = 40

#en

[[languages.en.menu.main]]
   identifier = "info"
   name = "Info"
   title = "Info"
   url = "/en/info"
   weight = 10
 [[languages.en.menu.main]]
   identifier = "articulos"
   name = "Articles"
   title = "Articles"
   url = "/en/articulos/"
   weight = 20
[[languages.en.menu.main]]
   identifier = "fotos"
   name = "Photo"
   title = "Photo"
   url = "/en/fotos/"
   weight = 30
[[languages.en.menu.main]]
  identifier = "reservas"
  name = "Bookings"
  title = "Bookings"
  url = "/en/reservas/"
  weight = 40

#it

  [[languages.it.menu.main]]
     identifier = "info"
     name = "Info"
     title = "Info"
     url = "/it/info"
     weight = 10
   [[languages.it.menu.main]]
     identifier = "articulos"
     name = "Articles"
     title = "Articles"
     url = "/it/articulos/"
     weight = 20
  [[languages.it.menu.main]]
     identifier = "fotos"
     name = "Photo"
     title = "Photo"
     url = "/it/fotos/"
     weight = 30
  [[languages.it.menu.main]]
    identifier = "reservas"
    name = "Riserva"
    title = "Riserva"
    url = "/it/reservas/"
    weight = 40